default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nutz_development
  username: root
  password: admin

test:
  <<: *default
  database: nutz_test
  username: root
  password: admin

production:
  <<: *default
  database: nutz_production
  username: root
  password: admin
